### ISSUE TITLE
when resource doesn't have any items in depend on it throws 404

### ISSUE THREAD

**Issue by Saifallak** [webparking/nova-belongs-to-dependency#4]
ex:

- belongsto Category
- dependonbelongsto book

if category doesn't have any books, it throws 404

**Comment by RVxLab** [comment]
Sorry for the late response on this. Does this still happen in Nova 4?

**Comment by Saifallak** [comment]
Idk, I don’t use nova 4 at all

**Comment by RVxLab** [comment]
@dgerrese @remkobrenters Can one of you take a look at this?

@Saifallak Can you provide a minimal example to help reproduce this issue? A private repo would be best.

**Comment by Saifallak** [comment]
Sorry, i don't have nova lic. Anymore, so can't do it

**Comment by remkobrenters** [comment]
@dgerrese can you schedule this one to take a look?

**Comment by dgerrese** [comment]
@remkobrenters I'll have a look later this week.

**Comment by dgerrese** [comment]
@remkobrenters Unfortunately, I could not reproduce this.

Until we have a way to reproduce this, I will close this issue.

If anyone can provide steps to reproduce this issue, please feel free to open a new bug report.
