### ISSUE TITLE
This package should be listed on Nova Packages

### ISSUE THREAD

**Issue by mrleblanc101** [webparking/nova-belongs-to-dependency#6]
Shouldn't this package be listed on Nova Packages ? https://novapackages.com/
I only see this which seem to be v3 only and abandonned. https://novapackages.com/packages/sanderbaas/laravel-nova-belongsto-dependency

**Comment by joserick** [comment]
@RVxLab  Yes, it is important to add it to https://novapackages.com/

**Comment by RVxLab** [comment]
Cheers for bringing this up, [the package has been added](https://novapackages.com/packages/webparking/nova-belongs-to-dependency).

@dgerrese it's under my wing on novapackages.com, let me know if you or someone else at Webparking wants to take that over.
