### ISSUE TITLE
Missing value on relationship and index

### ISSUE THREAD

**Issue by mrleblanc101** [webparking/nova-belongs-to-dependency#8]
On form, the value is correctly selected in the dropdown based on the dependsOn field.
![Capture d’écran, le 2022-10-11 à 11 43 55](https://user-images.githubusercontent.com/17392251/195138609-25d709a9-539b-4341-aac1-487cbc3510a7.png)

But on relationship view, the column is empty.
![Capture d’écran, le 2022-10-11 à 11 44 01](https://user-images.githubusercontent.com/17392251/195138634-d27606e2-7143-4d31-8c83-9f33efcd61f3.png)

**Comment by mrleblanc101** [comment]
The component doesn't seem to load.
![Capture d’écran, le 2022-10-11 à 14 18 12](https://user-images.githubusercontent.com/17392251/195169488-6d9b1d0f-01c7-49bd-8dab-2e327649e34c.png)

**Comment by ronaldvaneede** [comment]
I'm having the same problem
I might be able to create a fix but never worked with custom Nova field packages yet so I first need to see how that works in the first place.

**Comment by joserick** [comment]
@RVxLab Same problem, Any idea how to solve it?

**Comment by RVxLab** [comment]
> @RVxLab Same problem, Any idea how to solve it?

I don't have a Nova 4 license, so I'm unable to check this out.

> I'm having the same problem I might be able to create a fix but never worked with custom Nova field packages yet so I first need to see how that works in the first place.

If you could find the time to help out that would be amazing! It's not much different to creating your own local fields, except that they come from a different package.

You can clone the repo, then reference `dev-master` as the version for this package. Then you can add a local path [as described here](https://getcomposer.org/doc/05-repositories.md#path).

**Comment by joserick** [comment]
Hi @RVxLab 

In the end, he invested a couple of hours to see why it didn't work and in the end it was so simple like that it wasn't loading the views for index and detail, but hey, I already sent the pull request #9, do you know the username of someone from webparking? to send him a message and accept the changes.

**Comment by RVxLab** [comment]
I do, tagged someone from Webparking in the PR.
